(()=>{'use strict';
const $=s=>document.querySelector(s);const ALLOWED_SIZES=[8,16,32,64,128],HISTORY_LIMIT=80,JSON_LIMIT=5*1024*1024,AUTOSAVE_KEY='pixel-lite-project-v2';let lang=localStorage.getItem('pixel-lite-language')||'ja',size=32,color='#d45cf0',tool='pencil',mirrorX=false,mirrorY=false,pixels=[],undoStack=[],redoStack=[],dragging=false,lastPoint=null,gestureBefore=null,statusTimer=null;
const P={ja:{title:'PIXEL LITE — ピクセルアートエディタ',crumb:'A focused pixel desk for the web',tools:'TOOLS',pencil:'ペン',eraser:'消しゴム',fill:'塗りつぶし',pick:'スポイト',color:'色',palette:'パレット',canvas:'キャンバス',symmetry:'ミラー',horizontal:'左右',vertical:'上下',showGrid:'グリッド',undo:'元に戻す',redo:'やり直す',clear:'クリア',ready:'キャンバス準備完了',saveData:'プロジェクト保存',loadData:'プロジェクト読込',importImage:'画像を読み込む',exportScale:'PNG倍率',export:'PNGを書き出す',workbench:'WORKBENCH',makeTitle:'小さく描いて、\n壊さず残す。',painted:'塗ったピクセル',autosave:'自動保存',restored:'前回の作業を復元しました',saved:'PNGを保存しました',dataSaved:'プロジェクトを保存しました',loaded:'プロジェクトを読み込みました',invalid:'ファイルを読み込めません',tooLarge:'ファイルが大きすぎます',resized:'キャンバスをリサイズしました',imageLoaded:'画像をピクセル化しました',shortcuts:'SHORTCUTS',privacy:'画像とプロジェクトはブラウザ内で処理されます。'},en:{title:'PIXEL LITE — Pixel art editor',crumb:'A focused pixel desk for the web',tools:'TOOLS',pencil:'Pencil',eraser:'Eraser',fill:'Fill',pick:'Picker',color:'Color',palette:'Palette',canvas:'Canvas',symmetry:'Mirror',horizontal:'Horizontal',vertical:'Vertical',showGrid:'Grid',undo:'Undo',redo:'Redo',clear:'Clear',ready:'Canvas ready',saveData:'Save project',loadData:'Load project',importImage:'Import image',exportScale:'PNG scale',export:'Export PNG',workbench:'WORKBENCH',makeTitle:'Draw small.\nKeep it safe.',painted:'painted pixels',autosave:'Autosave',restored:'Previous work restored',saved:'PNG saved',dataSaved:'Project saved',loaded:'Project loaded',invalid:'Could not read file',tooLarge:'File is too large',resized:'Canvas resized',imageLoaded:'Image pixelated',shortcuts:'SHORTCUTS',privacy:'Images and projects are processed locally in your browser.'}};const t=k=>(P[lang]||P.en)[k]||k;const canvas=$('#canvas'),ctx=canvas.getContext('2d',{alpha:true});
function setStatus(s){clearTimeout(statusTimer);$('#status').textContent=s;statusTimer=setTimeout(()=>$('#status').textContent=t('ready'),2200)}function validColor(v){return typeof v==='string'&&/^#[0-9a-f]{6}$/i.test(v)}function clonePixels(p=pixels){return p.slice()}function projectSnapshot(){return{size,pixels:clonePixels()}}function samePixels(a,b){if(a.length!==b.length)return false;for(let i=0;i<a.length;i++)if(a[i]!==b[i])return false;return true}
function applyLanguage(){document.documentElement.lang=lang;document.title=t('title');document.querySelectorAll('[data-i18n]').forEach(e=>{if((P[lang]||P.en)[e.dataset.i18n]!=null)e.textContent=t(e.dataset.i18n)});$('#languageSelect').value=lang;$('#undo').title=t('undo');$('#redo').title=t('redo')}
function initBlank(nextSize=size){size=nextSize;pixels=Array(size*size).fill(null);undoStack=[];redoStack=[];syncSizeUi();draw();updateHistoryButtons();autosave()}
function syncSizeUi(){$('#gridSize').value=String(size);$('#canvasShell').style.setProperty('--grid-size',size)}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);const cell=canvas.width/size;for(let y=0;y<size;y++)for(let x=0;x<size;x++){const c=pixels[y*size+x];if(c){ctx.fillStyle=c;ctx.fillRect(Math.floor(x*cell),Math.floor(y*cell),Math.ceil(cell+.25),Math.ceil(cell+.25))}}$('#canvasShell').style.setProperty('--grid',$('#showGrid').checked?'#0003':'transparent');let count=0;for(const p of pixels)if(p)count++;$('#pixelCount').textContent=count.toLocaleString();$('#projectSize').textContent=`${size} × ${size}`}
function pushUndo(state=projectSnapshot()){undoStack.push({size:state.size,pixels:state.pixels.slice()});if(undoStack.length>HISTORY_LIMIT)undoStack.shift();redoStack=[];updateHistoryButtons()}function updateHistoryButtons(){$('#undo').disabled=!undoStack.length;$('#redo').disabled=!redoStack.length}function restoreState(s){size=s.size;pixels=s.pixels.slice();syncSizeUi();draw();autosave()}function undo(){if(!undoStack.length)return;redoStack.push(projectSnapshot());restoreState(undoStack.pop());updateHistoryButtons()}function redo(){if(!redoStack.length)return;undoStack.push(projectSnapshot());restoreState(redoStack.pop());updateHistoryButtons()}
function autosave(){try{localStorage.setItem(AUTOSAVE_KEY,JSON.stringify({version:2,size,pixels}))}catch{}}function restoreAutosave(){try{const raw=localStorage.getItem(AUTOSAVE_KEY);if(!raw)return false;const d=JSON.parse(raw);const v=validateProject(d);size=v.size;pixels=v.pixels;syncSizeUi();draw();return true}catch{return false}}
function validateProject(d){if(!d||typeof d!=='object')throw new Error('invalid');const s=Number(d.size);if(!ALLOWED_SIZES.includes(s)||!Array.isArray(d.pixels)||d.pixels.length!==s*s)throw new Error('invalid');const p=d.pixels.map(v=>v==null?null:(validColor(v)?v.toLowerCase():(()=>{throw new Error('invalid')})()));return{size:s,pixels:p}}
function cellFromEvent(e){const r=canvas.getBoundingClientRect();const x=Math.floor((e.clientX-r.left)/r.width*size),y=Math.floor((e.clientY-r.top)/r.height*size);return{x:Math.max(0,Math.min(size-1,x)),y:Math.max(0,Math.min(size-1,y))}}
function setPixel(x,y,c){if(x<0||y<0||x>=size||y>=size)return;pixels[y*size+x]=c;if(mirrorX)pixels[y*size+(size-1-x)]=c;if(mirrorY)pixels[(size-1-y)*size+x]=c;if(mirrorX&&mirrorY)pixels[(size-1-y)*size+(size-1-x)]=c}
function line(a,b,c){let x0=a.x,y0=a.y,x1=b.x,y1=b.y,dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,err=dx+dy;for(;;){setPixel(x0,y0,c);if(x0===x1&&y0===y1)break;const e2=2*err;if(e2>=dy){err+=dy;x0+=sx}if(e2<=dx){err+=dx;y0+=sy}}}
function flood(x,y,c){const old=pixels[y*size+x];if(old===c)return false;const seen=new Uint8Array(size*size),qx=new Int16Array(size*size),qy=new Int16Array(size*size);let head=0,tail=0;qx[tail]=x;qy[tail++]=y;while(head<tail){const a=qx[head],b=qy[head++],idx=b*size+a;if(seen[idx]||pixels[idx]!==old)continue;seen[idx]=1;pixels[idx]=c;if(a>0){qx[tail]=a-1;qy[tail++]=b}if(a<size-1){qx[tail]=a+1;qy[tail++]=b}if(b>0){qx[tail]=a;qy[tail++]=b-1}if(b<size-1){qx[tail]=a;qy[tail++]=b+1}}return true}
function selectTool(next){tool=next;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===next))}
function beginGesture(e){const p=cellFromEvent(e);if(tool==='pick'){const picked=pixels[p.y*size+p.x];if(picked){color=picked;$('#color').value=color;$('#hex').textContent=color.toUpperCase();syncPalette()}selectTool('pencil');return}gestureBefore=projectSnapshot();if(tool==='fill'){if(flood(p.x,p.y,color))commitGesture();return}dragging=true;lastPoint=p;canvas.setPointerCapture?.(e.pointerId);line(p,p,tool==='eraser'?null:color);draw()}
function moveGesture(e){if(!dragging||!lastPoint)return;const p=cellFromEvent(e);if(p.x===lastPoint.x&&p.y===lastPoint.y)return;line(lastPoint,p,tool==='eraser'?null:color);lastPoint=p;draw()}
function endGesture(){if(!dragging)return;dragging=false;lastPoint=null;commitGesture()}function commitGesture(){if(!gestureBefore)return;if(!samePixels(gestureBefore.pixels,pixels)||gestureBefore.size!==size){pushUndo(gestureBefore);draw();autosave()}gestureBefore=null;updateHistoryButtons()}
function resizeProject(next){if(!ALLOWED_SIZES.includes(next)||next===size)return;const before=projectSnapshot(),out=Array(next*next).fill(null);for(let y=0;y<next;y++)for(let x=0;x<next;x++){const sx=Math.min(size-1,Math.floor(x*size/next)),sy=Math.min(size-1,Math.floor(y*size/next));out[y*next+x]=pixels[sy*size+sx]}pushUndo(before);size=next;pixels=out;syncSizeUi();draw();autosave();setStatus(t('resized'))}
function clearCanvas(){if(!pixels.some(Boolean))return;pushUndo();pixels.fill(null);draw();autosave()}
function rotate90(){pushUndo();const out=Array(size*size).fill(null);for(let y=0;y<size;y++)for(let x=0;x<size;x++)out[x*size+(size-1-y)]=pixels[y*size+x];pixels=out;draw();autosave()}function flipHorizontal(){pushUndo();const out=Array(size*size);for(let y=0;y<size;y++)for(let x=0;x<size;x++)out[y*size+(size-1-x)]=pixels[y*size+x];pixels=out;draw();autosave()}
function outputCanvas(mult){const out=document.createElement('canvas');out.width=size*mult;out.height=size*mult;const o=out.getContext('2d',{alpha:true});o.imageSmoothingEnabled=false;for(let y=0;y<size;y++)for(let x=0;x<size;x++){const c=pixels[y*size+x];if(c){o.fillStyle=c;o.fillRect(x*mult,y*mult,mult,mult)}}return out}async function canvasBlob(c){return await new Promise(r=>c.toBlob(r,'image/png'))}function downloadBlob(name,blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1200)}async function exportPng(){const mult=Number($('#exportScale').value)||1,blob=await canvasBlob(outputCanvas(mult));if(blob){downloadBlob(`pixel-lite-${size}x${size}-${mult}x.png`,blob);setStatus(t('saved'))}}
function saveProject(){const blob=new Blob([JSON.stringify({version:2,size,pixels},null,2)],{type:'application/json'});downloadBlob('pixel-lite-project.json',blob);setStatus(t('dataSaved'))}async function importProject(file){if(!file)return;if(file.size>JSON_LIMIT){setStatus(t('tooLarge'));return}try{const d=validateProject(JSON.parse(await file.text()));pushUndo();size=d.size;pixels=d.pixels;syncSizeUi();draw();autosave();setStatus(t('loaded'))}catch{setStatus(t('invalid'))}finally{$('#importJson').value=''}}
async function importImage(file){if(!file)return;if(file.size>25*1024*1024){setStatus(t('tooLarge'));return}try{let bmp;if('createImageBitmap'in window)bmp=await createImageBitmap(file,{imageOrientation:'from-image'});else bmp=await new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),i=new Image();i.onload=()=>{URL.revokeObjectURL(u);resolve(i)};i.onerror=()=>{URL.revokeObjectURL(u);reject()};i.src=u});const tmp=document.createElement('canvas');tmp.width=size;tmp.height=size;const c=tmp.getContext('2d',{willReadFrequently:true});c.imageSmoothingEnabled=false;c.clearRect(0,0,size,size);const ratio=Math.min(size/(bmp.width||bmp.naturalWidth),size/(bmp.height||bmp.naturalHeight)),w=Math.max(1,Math.round((bmp.width||bmp.naturalWidth)*ratio)),h=Math.max(1,Math.round((bmp.height||bmp.naturalHeight)*ratio));c.drawImage(bmp,Math.floor((size-w)/2),Math.floor((size-h)/2),w,h);const data=c.getImageData(0,0,size,size).data,out=Array(size*size).fill(null);for(let i=0;i<out.length;i++){const a=data[i*4+3];if(a<32)continue;out[i]='#'+[data[i*4],data[i*4+1],data[i*4+2]].map(v=>v.toString(16).padStart(2,'0')).join('')}bmp.close?.();pushUndo();pixels=out;draw();autosave();setStatus(t('imageLoaded'))}catch{setStatus(t('invalid'))}finally{$('#importImage').value=''}}
const PALETTE=['#d45cf0','#f56b6b','#ffb84d','#f4e46b','#79d16c','#51c7a6','#6fa8ff','#9277d6','#f5edff','#3a3542'];function renderPalette(){const box=$('#palette');box.replaceChildren();for(const c of PALETTE){const b=document.createElement('button');b.type='button';b.className='swatch';b.style.background=c;b.dataset.color=c;b.setAttribute('aria-label',c);b.onclick=()=>{color=c;$('#color').value=c;$('#hex').textContent=c.toUpperCase();syncPalette()};box.append(b)}syncPalette()}function syncPalette(){document.querySelectorAll('.swatch').forEach(b=>b.classList.toggle('active',b.dataset.color.toLowerCase()===color.toLowerCase()))}
function shortcut(e){const tag=e.target?.tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag)||e.target?.isContentEditable)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(e.shiftKey)redo();else undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(e.key.toLowerCase()==='p')selectTool('pencil');else if(e.key.toLowerCase()==='e')selectTool('eraser');else if(e.key.toLowerCase()==='g')selectTool('fill');else if(e.key.toLowerCase()==='i')selectTool('pick')}
function init(){applyLanguage();renderPalette();if(!restoreAutosave())initBlank(size);else{undoStack=[];redoStack=[];updateHistoryButtons();setStatus(t('restored'))}$('#color').value=color;$('#hex').textContent=color.toUpperCase();document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>selectTool(b.dataset.tool));$('#color').oninput=e=>{color=e.target.value.toLowerCase();$('#hex').textContent=color.toUpperCase();syncPalette()};$('#showGrid').onchange=draw;$('#mirrorX').onclick=()=>{mirrorX=!mirrorX;$('#mirrorX').classList.toggle('active',mirrorX)};$('#mirrorY').onclick=()=>{mirrorY=!mirrorY;$('#mirrorY').classList.toggle('active',mirrorY)};$('#gridSize').onchange=e=>resizeProject(Number(e.target.value));$('#undo').onclick=undo;$('#redo').onclick=redo;$('#clear').onclick=clearCanvas;$('#rotate').onclick=rotate90;$('#flip').onclick=flipHorizontal;$('#exportButton').onclick=exportPng;$('#exportJson').onclick=saveProject;$('#importJson').onchange=e=>importProject(e.target.files?.[0]);$('#importImage').onchange=e=>importImage(e.target.files?.[0]);canvas.onpointerdown=beginGesture;canvas.onpointermove=moveGesture;canvas.onpointerup=endGesture;canvas.onpointercancel=endGesture;canvas.oncontextmenu=e=>e.preventDefault();document.addEventListener('keydown',shortcut);$('#languageSelect').onchange=e=>{lang=e.target.value;localStorage.setItem('pixel-lite-language',lang);applyLanguage()};selectTool('pencil')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();