(()=>{'use strict';
const COMMON_API='https://form-lens-api.hurukigeoetym.workers.dev';
const MAX_FILE_BYTES=100*1024*1024,MAX_BATCH_FILES=40,MAX_BATCH_INPUT=300*1024*1024,MAX_CANVAS_PIXELS=40_000_000,MAX_ZIP_BYTES=200*1024*1024;
const $=s=>document.querySelector(s),fileInput=$('#fileInput'),dropZone=$('#dropZone'),controls=$('#controls'),quality=$('#quality'),format=$('#outputFormat'),resize=$('#maxEdge'),originalSize=$('#originalSize'),compressedSize=$('#compressedSize'),savedSize=$('#savedSize'),dimensions=$('#dimensions'),outputDimensions=$('#outputDimensions'),downloadButton=$('#downloadButton'),status=$('#status'),preview=$('#preview');
const TEXT={ja:{ready:'画像を選んでください。',working:'処理中…',done:'処理が完了しました。',stale:'設定が変わりました。「選択画像を処理」で更新してください。',bad:'読み込めない画像があります。',tooMany:'最大40枚までです。',tooLarge:'1枚100MB、合計300MBまでです。',zipTooLarge:'ZIP対象が200MBを超えます。個別保存してください。',targetMiss:'目標容量には届きませんでした',process:'選択画像を処理',zip:'ZIPでまとめて保存',clear:'クリア',target:'目標容量（任意）',targetNote:'JPEG/WebPのみ。指定KB以下で可能な限り高品質を探索します。',batchEmpty:'処理する画像がここに並びます。',queued:'待機',processing:'処理中',staleState:'要再処理',error:'エラー',select:'枚選択',saved:'保存しました',drop:'画像を選択・複数ドロップ',download:'選択画像を保存',hero:'画像を、<br><span>まとめて軽くする。</span>',lede:'アップロード不要。最大40枚を順番に処理し、同じ形式・サイズ・品質・目標容量をまとめて適用できます。'},en:{ready:'Choose images to begin.',working:'Processing…',done:'Processing complete.',stale:'Settings changed. Run “Process selected images” to refresh outputs.',bad:'Some images could not be processed.',tooMany:'Up to 40 images are supported.',tooLarge:'Limit: 100 MB per image and 300 MB total.',zipTooLarge:'ZIP output exceeds 200 MB. Save files individually.',targetMiss:'Target size could not be reached',process:'Process selected images',zip:'Save all as ZIP',clear:'Clear',target:'Target size (optional)',targetNote:'JPEG/WebP only. Finds the highest quality at or below the target KB when possible.',batchEmpty:'Selected images will appear here.',queued:'Queued',processing:'Processing',staleState:'Needs refresh',error:'Error',select:'selected',saved:'Saved',drop:'Choose or drop multiple images',download:'Save selected image',hero:'Make images<br><span>lighter in batches.</span>',lede:'No upload. Process up to 40 images sequentially with one format, resize, quality and optional target size.'},zh:{ready:'请选择图片。',working:'处理中…',done:'处理完成。',stale:'设置已更改，请重新处理。',bad:'部分图片无法处理。',tooMany:'最多40张图片。',tooLarge:'单张100MB、合计300MB以内。',zipTooLarge:'ZIP内容超过200MB，请单独保存。',targetMiss:'无法达到目标大小',process:'处理所选图片',zip:'保存为ZIP',clear:'清空',target:'目标大小（可选）',targetNote:'仅JPEG/WebP。尽量在目标KB以内寻找最高质量。',batchEmpty:'所选图片会显示在这里。',queued:'等待',processing:'处理中',staleState:'需重新处理',error:'错误',select:'张已选',saved:'已保存',drop:'选择或拖放多张图片',download:'保存所选图片',hero:'批量让图片，<br><span>更轻。</span>',lede:'无需上传。最多40张图片按顺序在浏览器中处理。'},ko:{ready:'이미지를 선택하세요.',working:'처리 중…',done:'처리가 완료되었습니다.',stale:'설정이 바뀌었습니다. 다시 처리해 주세요.',bad:'일부 이미지를 처리할 수 없습니다.',tooMany:'최대 40장까지 지원합니다.',tooLarge:'한 장 100MB, 총 300MB까지입니다.',zipTooLarge:'ZIP 대상이 200MB를 넘습니다. 개별 저장해 주세요.',targetMiss:'목표 용량에 도달하지 못했습니다',process:'선택 이미지 처리',zip:'ZIP으로 저장',clear:'지우기',target:'목표 용량(선택)',targetNote:'JPEG/WebP 전용. 목표 KB 이하에서 가능한 최고 품질을 찾습니다.',batchEmpty:'선택한 이미지가 여기에 표시됩니다.',queued:'대기',processing:'처리 중',staleState:'재처리 필요',error:'오류',select:'장 선택',saved:'저장됨',drop:'여러 이미지 선택 또는 드롭',download:'선택 이미지 저장',hero:'이미지를<br><span>한꺼번에 가볍게.</span>',lede:'업로드 없이 최대 40장을 순차 처리합니다.'}};
let lang=localStorage.getItem('site-language')||'ja',items=[],selected=0,generation=0,previewUrl=null,totalOutput=0;
const t=k=>(TEXT[lang]||TEXT.en)[k]||k;
function reportVisit(){fetch(`${COMMON_API}/api/events`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({site:'image-shrink-jp',eventName:'page_view'})}).catch(()=>{})}
function fmt(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(2)} MB`}
function setStatus(s,type=''){status.textContent=s;status.classList.toggle('is-error',type==='error');status.classList.toggle('is-working',type==='working');status.classList.toggle('is-success',type==='success')}
function safeBase(name){return(String(name||'image').replace(/\.[^.]+$/,'')||'image').replace(/[\\/:*?"<>|\x00-\x1f]/g,'_').slice(0,100)}
function injectBatchUi(){
  fileInput.multiple=true;$('#dropLabel').textContent=t('drop');
  const adv=$('.advanced-controls');
  if(!$('#targetKb')){const block=document.createElement('div');block.className='control-block';block.innerHTML='<label id="targetLabel" for="targetKb"></label><input id="targetKb" type="number" min="50" max="20000" step="50" inputmode="numeric" placeholder="500"><p class="target-note" id="targetNote"></p>';adv.append(block)}
  if(!$('#batchActions')){const area=document.createElement('div');area.id='batchActions';area.className='batch-actions';const process=document.createElement('button');process.id='processAll';process.type='button';process.className='button button-primary';const zip=document.createElement('button');zip.id='downloadAll';zip.type='button';zip.className='button';zip.disabled=true;const clear=document.createElement('button');clear.id='clearBatch';clear.type='button';clear.className='button';const summary=document.createElement('span');summary.id='batchSummary';summary.className='batch-summary';area.append(process,zip,clear,summary);const queue=document.createElement('div');queue.id='batchQueue';queue.className='batch-queue';$('.image-meta').before(area,queue);process.onclick=processAll;zip.onclick=downloadZip;clear.onclick=clearBatch}
  $('#targetLabel').textContent=t('target');$('#targetNote').textContent=t('targetNote');$('#processAll').textContent=t('process');$('#downloadAll').textContent=t('zip');$('#clearBatch').textContent=t('clear');downloadButton.textContent=t('download');
}
function applyLanguage(){document.documentElement.lang=lang;$('#languageSelect').value=lang;injectBatchUi();$('#dropLabel').textContent=t('drop');const h=$('.compress-hero h1');if(h)h.innerHTML=t('hero');const lede=$('.compress-hero .lede');if(lede)lede.textContent=t('lede');if(!items.length)setStatus(t('ready'));renderQueue()}
function settings(){const target=Math.max(0,Math.min(20000,Number($('#targetKb')?.value)||0));return{format:format.value,maxEdge:resize.value,quality:Number(quality.value)/100,targetBytes:target?target*1024:0}}
function signature(){return JSON.stringify(settings())}
function syncControls(){const png=format.value==='png';quality.disabled=png;$('#targetKb').disabled=png;const q=$('#qualityValue');if(q)q.textContent=quality.value}
function clearPreview(){if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null}preview.removeAttribute('src')}
function updateCurrent(){clearPreview();const item=items[selected];if(!item){dimensions.textContent=outputDimensions.textContent=originalSize.textContent=compressedSize.textContent=savedSize.textContent='—';downloadButton.classList.add('disabled');downloadButton.setAttribute('aria-disabled','true');return}dimensions.textContent=item.sourceDims||'—';originalSize.textContent=fmt(item.file.size);if(item.blob&&item.sig===signature()){previewUrl=URL.createObjectURL(item.blob);preview.src=previewUrl;compressedSize.textContent=fmt(item.blob.size);outputDimensions.textContent=item.outputDims||'—';const saved=Math.round((1-item.blob.size/item.file.size)*100);savedSize.textContent=saved>=0?`${saved}%`:`+${Math.abs(saved)}%`;downloadButton.classList.remove('disabled');downloadButton.setAttribute('aria-disabled','false')}else{compressedSize.textContent=outputDimensions.textContent=savedSize.textContent='—';downloadButton.classList.add('disabled');downloadButton.setAttribute('aria-disabled','true')}}
function renderQueue(){const box=$('#batchQueue');if(!box)return;box.replaceChildren();if(!items.length){const e=document.createElement('div');e.className='batch-empty';e.textContent=t('batchEmpty');box.append(e);$('#batchSummary').textContent='—';$('#downloadAll').disabled=true;return}const sig=signature();let ready=0,failed=0;items.forEach((item,i)=>{const b=document.createElement('button');b.type='button';b.className='batch-item'+(i===selected?' active':'');let state=t('queued'),cls='';if(item.status==='working'){state=t('processing');cls=' is-working'}else if(item.error){state=t('error');cls=' is-error';failed++}else if(item.blob&&item.sig===sig){state=fmt(item.blob.size)+(item.targetMiss?' · '+t('targetMiss'):'');ready++}else if(item.blob){state=t('staleState');cls=' is-stale'}b.className+=cls;const name=document.createElement('strong');name.textContent=item.file.name;const meta=document.createElement('span');meta.textContent=`${fmt(item.file.size)}${item.outputDims?' → '+item.outputDims:''}`;const st=document.createElement('span');st.className='batch-state';st.textContent=state;b.append(name,meta,st);b.onclick=()=>{selected=i;renderQueue();updateCurrent()};box.append(b)});$('#batchSummary').textContent=`${items.length} ${t('select')} · ${ready} ready${failed?' · '+failed+' error':''}`;$('#downloadAll').disabled=ready<2||items.some(x=>x.blob&&x.sig!==sig)||items.some(x=>x.status==='working')}
async function decode(file){if('createImageBitmap'in window){try{return await createImageBitmap(file,{imageOrientation:'from-image'})}catch{}}return await new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(u);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('decode'))};img.src=u})}
function sourceSize(src){return[src.width||src.naturalWidth||0,src.height||src.naturalHeight||0]}
function targetSize(sw,sh,s){let scale=1;if(s.maxEdge!=='original'){const cap=Number(s.maxEdge);if(cap>0)scale=Math.min(1,cap/Math.max(sw,sh))}let w=Math.max(1,Math.round(sw*scale)),h=Math.max(1,Math.round(sh*scale));if(w*h>MAX_CANVAS_PIXELS){const k=Math.sqrt(MAX_CANVAS_PIXELS/(w*h));w=Math.max(1,Math.floor(w*k));h=Math.max(1,Math.floor(h*k))}return[w,h]}
function mimeExt(f){return f==='jpeg'?['image/jpeg','jpg']:f==='png'?['image/png','png']:['image/webp','webp']}
function canvasBlob(c,mime,q){return new Promise(r=>c.toBlob(r,mime,q))}
async function encodeWithTarget(canvas,mime,maxQ,target){if(mime==='image/png'||!target){const b=await canvasBlob(canvas,mime,mime==='image/png'?undefined:maxQ);if(!b)throw new Error('encode');return{blob:b,targetMiss:false}}
  let high=maxQ,first=await canvasBlob(canvas,mime,high);if(!first)throw new Error('encode');if(first.size<=target)return{blob:first,targetMiss:false};let low=.08,best=null;for(let i=0;i<7;i++){const q=(low+high)/2,b=await canvasBlob(canvas,mime,q);if(!b)throw new Error('encode');if(b.size<=target){best=b;low=q}else high=q}if(best)return{blob:best,targetMiss:false};const floor=await canvasBlob(canvas,mime,.08);if(!floor)throw new Error('encode');return{blob:floor,targetMiss:floor.size>target}}
async function processOne(item,s){let src=null;try{src=await decode(item.file);const[sw,sh]=sourceSize(src);if(!sw||!sh)throw new Error('decode');const[w,h]=targetSize(sw,sh,s),[mime,ext]=mimeExt(s.format),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const cx=canvas.getContext('2d',{alpha:mime!=='image/jpeg'});if(!cx)throw new Error('canvas');if(mime==='image/jpeg'){cx.fillStyle='#fff';cx.fillRect(0,0,w,h)}cx.imageSmoothingEnabled=true;cx.imageSmoothingQuality='high';cx.drawImage(src,0,0,w,h);const out=await encodeWithTarget(canvas,mime,s.quality,s.targetBytes);canvas.width=canvas.height=1;return{...out,ext,sourceDims:`${sw.toLocaleString()} × ${sh.toLocaleString()}`,outputDims:`${w.toLocaleString()} × ${h.toLocaleString()}`}}finally{try{src?.close?.()}catch{}}}
async function processAll(){if(!items.length)return;const token=++generation,s=settings(),sig=signature();totalOutput=0;$('#processAll').disabled=true;$('#downloadAll').disabled=true;setStatus(t('working'),'working');for(let i=0;i<items.length;i++){if(token!==generation)return;const item=items[i];item.status='working';item.error='';item.blob=null;renderQueue();try{const out=await processOne(item,s);if(token!==generation)return;item.blob=out.blob;item.ext=out.ext;item.sourceDims=out.sourceDims;item.outputDims=out.outputDims;item.targetMiss=out.targetMiss;item.sig=sig;totalOutput+=out.blob.size;if(totalOutput>300*1024*1024)throw new Error('output-limit')}catch(e){console.warn(e);item.error=String(e.message||e);item.blob=null}finally{item.status='';renderQueue();if(i===selected)updateCurrent();await new Promise(r=>setTimeout(r,0))}}$('#processAll').disabled=false;const failed=items.some(x=>x.error);setStatus(failed?t('bad'):t('done'),failed?'error':'success');renderQueue();updateCurrent()}
function markStale(){syncControls();if(!items.length)return;renderQueue();updateCurrent();if(items.length===1){clearTimeout(markStale.timer);markStale.timer=setTimeout(processAll,220)}else setStatus(t('stale'))}
function acceptFiles(list){const files=[...list].filter(f=>/^image\/(?:jpeg|png|webp)$/i.test(f.type)||/\.(?:jpe?g|png|webp)$/i.test(f.name));if(files.length>MAX_BATCH_FILES){setStatus(t('tooMany'),'error');return}if(files.some(f=>f.size>MAX_FILE_BYTES)||files.reduce((a,f)=>a+f.size,0)>MAX_BATCH_INPUT){setStatus(t('tooLarge'),'error');return}generation++;items=files.map((file,i)=>({id:Date.now()+i,file,status:'',error:'',blob:null,sig:''}));selected=0;controls.hidden=!items.length;renderQueue();updateCurrent();if(items.length)processAll();else setStatus(t('ready'))}
function clearBatch(){generation++;items=[];selected=0;totalOutput=0;fileInput.value='';clearPreview();controls.hidden=true;renderQueue();updateCurrent();setStatus(t('ready'))}
function downloadBlob(name,blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function currentDownload(){const item=items[selected];if(!item?.blob||item.sig!==signature())return;downloadBlob(`${safeBase(item.file.name)}-compressed.${item.ext}`,item.blob)}
const CRC_TABLE=(()=>{const a=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;a[n]=c>>>0}return a})();
function crc32(data){let c=0xffffffff;for(const b of data)c=CRC_TABLE[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function dosDateTime(d=new Date()){const year=Math.max(1980,d.getFullYear());return{time:(d.getHours()<<11)|(d.getMinutes()<<5)|(d.getSeconds()>>1),date:((year-1980)<<9)|((d.getMonth()+1)<<5)|d.getDate()}}
function bytes(n,write){const a=new Uint8Array(n),v=new DataView(a.buffer);write(v,a);return a}
function uniqueNames(list){const used=new Set();return list.map(x=>{const base=`${safeBase(x.file.name)}-compressed.${x.ext}`;if(!used.has(base)){used.add(base);return base}let i=2,name;do{name=base.replace(/(\.[^.]+)$/,`-${i++}$1`)}while(used.has(name));used.add(name);return name})}
async function makeZip(valid){const total=valid.reduce((a,x)=>a+x.blob.size,0);if(total>MAX_ZIP_BYTES)throw new Error('zip-large');const names=uniqueNames(valid),parts=[],central=[];let offset=0;const enc=new TextEncoder(),dt=dosDateTime();for(let i=0;i<valid.length;i++){const data=new Uint8Array(await valid[i].blob.arrayBuffer()),name=enc.encode(names[i]),crc=crc32(data),local=bytes(30+name.length,(v,a)=>{v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x0800,true);v.setUint16(8,0,true);v.setUint16(10,dt.time,true);v.setUint16(12,dt.date,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);v.setUint16(28,0,true);a.set(name,30)});parts.push(local,data);const cd=bytes(46+name.length,(v,a)=>{v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint16(8,0x0800,true);v.setUint16(10,0,true);v.setUint16(12,dt.time,true);v.setUint16(14,dt.date,true);v.setUint32(16,crc,true);v.setUint32(20,data.length,true);v.setUint32(24,data.length,true);v.setUint16(28,name.length,true);v.setUint16(30,0,true);v.setUint16(32,0,true);v.setUint16(34,0,true);v.setUint16(36,0,true);v.setUint32(38,0,true);v.setUint32(42,offset,true);a.set(name,46)});central.push(cd);offset+=local.length+data.length}const centralOffset=offset,centralSize=central.reduce((a,x)=>a+x.length,0),end=bytes(22,v=>{v.setUint32(0,0x06054b50,true);v.setUint16(4,0,true);v.setUint16(6,0,true);v.setUint16(8,valid.length,true);v.setUint16(10,valid.length,true);v.setUint32(12,centralSize,true);v.setUint32(16,centralOffset,true);v.setUint16(20,0,true)});return new Blob([...parts,...central,end],{type:'application/zip'})}
async function downloadZip(){const sig=signature(),valid=items.filter(x=>x.blob&&x.sig===sig);if(valid.length<2)return;try{setStatus(t('working'),'working');const zip=await makeZip(valid);downloadBlob(`compressed-images-${new Date().toISOString().slice(0,10)}.zip`,zip);setStatus(t('saved'),'success')}catch(e){setStatus(e.message==='zip-large'?t('zipTooLarge'):t('bad'),'error')}}
fileInput.addEventListener('change',()=>acceptFiles(fileInput.files||[]));['dragenter','dragover'].forEach(n=>dropZone.addEventListener(n,e=>{e.preventDefault();dropZone.classList.add('is-dragover')}));['dragleave','drop'].forEach(n=>dropZone.addEventListener(n,e=>{e.preventDefault();dropZone.classList.remove('is-dragover')}));dropZone.addEventListener('drop',e=>acceptFiles(e.dataTransfer.files||[]));quality.addEventListener('input',markStale);format.addEventListener('change',markStale);resize.addEventListener('change',markStale);downloadButton.addEventListener('click',e=>{e.preventDefault();currentDownload()});$('#languageSelect').addEventListener('change',e=>{lang=e.target.value;localStorage.setItem('site-language',lang);applyLanguage()});window.addEventListener('beforeunload',()=>{generation++;clearPreview()});injectBatchUi();$('#targetKb').addEventListener('input',markStale);syncControls();applyLanguage();renderQueue();reportVisit();})();