const COMMON_API='https://form-lens-api.hurukigeoetym.workers.dev';
function reportVisit(){fetch(`${COMMON_API}/api/events`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({site:'image-shrink-jp',eventName:'page_view'})}).catch(()=>{})}
const PACKS={
ja:{title:'画像圧縮｜ブラウザだけで軽くする無料ツール',desc:'JPEG・PNG・WebPをブラウザ内で圧縮・リサイズ・形式変換。画像をアップロードせず保存できます。',brand:'画像を軽くする帖',navCompress:'圧縮する',navPrivacy:'安全性',navUse:'無料で使う',eyebrow:'画像ツール / LOCAL',hero:'画像を、<br><span>軽くする。</span>',lede:'アップロード不要。形式・サイズ・品質を選んで、ブラウザ内だけで圧縮します。',panel:'画像圧縮',note:'ファイルは外へ送信しません',choose:'画像を選ぶ',drop:'画像をここに選択',quality:'圧縮品質',format:'出力形式',resize:'最大辺',original:'元のサイズ',compressed:'圧縮後',saved:'削減率',dimensions:'画像サイズ',outputDimensions:'出力サイズ',download:'圧縮画像を保存',ready:'画像を選んでください。',selectImage:'JPEG・PNG・WebP画像を選んでください。',updated:'圧縮結果を更新しました。',working:'圧縮しています…',tooLarge:'ファイルが大きすぎます（100MBまで）。',tooManyPixels:'画像が大きすぎます。最大辺を小さくしてください。',decodeError:'画像を読み込めませんでした。',encodeError:'この形式へ変換できませんでした。',privacy:'画像はブラウザ内だけで処理。',privacyCopy:'選んだ画像ファイル自体は外部サーバーへ送信しません。圧縮・リサイズ・形式変換は端末上で行います。',guideEyebrow:'HOW IT WORKS',guideTitle:'3つの操作で、<br>送れるサイズに。',g1:'画像を選ぶ',g1p:'JPEG・PNG・WebPを選択またはドロップ。',g2:'形式とサイズを調整',g2p:'WebP/JPEG/PNG、最大辺、品質を選べます。',g3:'確認して保存',g3p:'プレビューと容量を確認して端末へ保存します。',faq:'よくある質問',faqTitle:'軽くする前に。',faq1:'対応している画像形式は？',faq1p:'入力はJPEG・PNG・WebP、出力はWebP・JPEG・PNGです。PNGは品質スライダーを使いません。',faq2:'画像はアップロードされますか？',faq2p:'画像ファイルは送信しません。処理はブラウザ内で完結します。',faq3:'巨大画像はどうなりますか？',faq3p:'ブラウザのメモリ枯渇を防ぐため、処理キャンバスは約4000万画素を上限に自動縮小します。',footerCompress:'画像圧縮',footerPrivacy:'プライバシー'},
en:{title:'Image Compressor | Resize and convert locally',desc:'Compress, resize and convert JPEG, PNG and WebP locally in your browser without uploading the image.',brand:'Image Shrink Notes',navCompress:'Compress',navPrivacy:'Privacy',navUse:'Use free',eyebrow:'IMAGE TOOL / LOCAL',hero:'Make images<br><span>lighter.</span>',lede:'No upload needed. Choose format, dimensions and quality, then compress entirely in your browser.',panel:'Image compressor',note:'FILE NEVER LEAVES YOUR DEVICE',choose:'Choose image',drop:'Choose or drop an image',quality:'Quality',format:'Output format',resize:'Max edge',original:'Original',compressed:'Compressed',saved:'Saved',dimensions:'Image size',outputDimensions:'Output size',download:'Save compressed image',ready:'Choose an image to begin.',selectImage:'Choose a JPEG, PNG or WebP image.',updated:'Compression result updated.',working:'Compressing…',tooLarge:'File is too large (100 MB max).',tooManyPixels:'Image is too large. Choose a smaller max edge.',decodeError:'Could not decode this image.',encodeError:'Could not encode this format.',privacy:'Images stay in your browser.',privacyCopy:'The image file itself is never sent to an external server. Compression, resizing and conversion run on your device.',guideEyebrow:'HOW IT WORKS',guideTitle:'Three steps to a<br>sendable file.',g1:'Choose an image',g1p:'Choose or drop JPEG, PNG or WebP.',g2:'Tune format and size',g2p:'Choose WebP/JPEG/PNG, max edge and quality.',g3:'Preview and save',g3p:'Check dimensions and file size, then save locally.',faq:'FAQ',faqTitle:'Before you shrink.',faq1:'Which formats are supported?',faq1p:'Input supports JPEG, PNG and WebP. Output supports WebP, JPEG and PNG. PNG ignores the quality slider.',faq2:'Is my image uploaded?',faq2p:'No image file is uploaded. Processing happens in your browser.',faq3:'What about huge images?',faq3p:'To prevent browser memory exhaustion, the processing canvas is automatically kept around 40 megapixels or below.',footerCompress:'Image compressor',footerPrivacy:'Privacy'},
zh:{title:'图片压缩｜本地缩放与格式转换',desc:'在浏览器本地压缩、缩放和转换JPEG、PNG、WebP，不上传图片。',brand:'图片轻量册',navCompress:'压缩',navPrivacy:'安全性',navUse:'免费使用',eyebrow:'图片工具 / LOCAL',hero:'让图片，<br><span>更轻。</span>',lede:'无需上传。选择格式、尺寸和质量，在浏览器内完成处理。',panel:'图片压缩',note:'文件不会离开设备',choose:'选择图片',drop:'选择或拖放图片',quality:'压缩质量',format:'输出格式',resize:'最大边',original:'原始大小',compressed:'压缩后',saved:'减少率',dimensions:'图片尺寸',outputDimensions:'输出尺寸',download:'保存压缩图片',ready:'请选择图片。',selectImage:'请选择JPEG、PNG或WebP图片。',updated:'压缩结果已更新。',working:'正在压缩…',tooLarge:'文件过大（最大100MB）。',tooManyPixels:'图片过大，请选择较小的最大边。',decodeError:'无法读取图片。',encodeError:'无法转换为该格式。',privacy:'图片只在浏览器中处理。',privacyCopy:'图片文件不会发送到外部服务器。压缩、缩放和格式转换均在设备上完成。',guideEyebrow:'HOW IT WORKS',guideTitle:'三步操作，<br>得到易发送的大小。',g1:'选择图片',g1p:'选择或拖放JPEG、PNG、WebP。',g2:'调整格式与尺寸',g2p:'选择WebP/JPEG/PNG、最大边和质量。',g3:'预览并保存',g3p:'确认尺寸和文件大小后保存。',faq:'常见问题',faqTitle:'压缩之前。',faq1:'支持哪些格式？',faq1p:'输入支持JPEG、PNG、WebP；输出支持WebP、JPEG、PNG。PNG不使用质量滑块。',faq2:'图片会上传吗？',faq2p:'不会上传图片文件，处理在浏览器中完成。',faq3:'超大图片怎么办？',faq3p:'为避免浏览器内存不足，处理画布会自动限制在约4000万像素以内。',footerCompress:'图片压缩',footerPrivacy:'隐私'},
ko:{title:'이미지 압축 | 로컬 리사이즈 및 변환',desc:'JPEG, PNG, WebP를 업로드 없이 브라우저에서 압축, 리사이즈, 변환합니다.',brand:'이미지 가볍게 노트',navCompress:'압축하기',navPrivacy:'안전성',navUse:'무료 사용',eyebrow:'이미지 도구 / LOCAL',hero:'이미지를<br><span>가볍게.</span>',lede:'업로드 없이 형식, 크기, 품질을 선택해 브라우저 안에서 처리합니다.',panel:'이미지 압축',note:'파일은 기기를 떠나지 않습니다',choose:'이미지 선택',drop:'이미지 선택 또는 드롭',quality:'압축 품질',format:'출력 형식',resize:'최대 변',original:'원본 크기',compressed:'압축 후',saved:'절약률',dimensions:'이미지 크기',outputDimensions:'출력 크기',download:'압축 이미지 저장',ready:'이미지를 선택하세요.',selectImage:'JPEG, PNG 또는 WebP 이미지를 선택하세요.',updated:'압축 결과를 업데이트했습니다.',working:'압축 중…',tooLarge:'파일이 너무 큽니다 (최대100MB).',tooManyPixels:'이미지가 너무 큽니다. 더 작은 최대 변을 선택하세요.',decodeError:'이미지를 읽을 수 없습니다.',encodeError:'이 형식으로 변환할 수 없습니다.',privacy:'이미지는 브라우저 안에서만 처리됩니다.',privacyCopy:'이미지 파일은 외부 서버로 전송하지 않습니다. 압축, 리사이즈, 형식 변환은 기기에서 처리됩니다.',guideEyebrow:'HOW IT WORKS',guideTitle:'세 단계로<br>보내기 좋은 크기.',g1:'이미지 선택',g1p:'JPEG, PNG, WebP를 선택하거나 드롭하세요.',g2:'형식과 크기 조정',g2p:'WebP/JPEG/PNG, 최대 변, 품질을 선택합니다.',g3:'미리보기 후 저장',g3p:'크기와 용량을 확인하고 기기에 저장합니다.',faq:'자주 묻는 질문',faqTitle:'가볍게 만들기 전에.',faq1:'지원 형식은?',faq1p:'입력은JPEG, PNG, WebP, 출력은WebP, JPEG, PNG를 지원합니다. PNG는 품질 슬라이더를 사용하지 않습니다.',faq2:'이미지가 업로드되나요?',faq2p:'이미지 파일은 업로드되지 않으며 브라우저에서 처리됩니다.',faq3:'아주 큰 이미지는?',faq3p:'브라우저 메모리 부족을 막기 위해 처리 캔버스를 약4000만 픽셀 이하로 자동 제한합니다.',footerCompress:'이미지 압축',footerPrivacy:'개인정보'}
};
let currentLanguage=localStorage.getItem('site-language')||'ja';
const copy=()=>PACKS[currentLanguage]||PACKS.en;
const $=s=>document.querySelector(s);
const fileInput=$('#fileInput'),dropZone=$('#dropZone'),controls=$('#controls'),quality=$('#quality'),format=$('#outputFormat'),resize=$('#maxEdge'),originalSize=$('#originalSize'),compressedSize=$('#compressedSize'),savedSize=$('#savedSize'),dimensions=$('#dimensions'),outputDimensions=$('#outputDimensions'),downloadButton=$('#downloadButton'),status=$('#status'),preview=$('#preview');
const MAX_FILE_BYTES=100*1024*1024,MAX_CANVAS_PIXELS=40_000_000;
let sourceFile=null,source=null,sourceObjectUrl=null,outputUrl=null,encodeToken=0,debounceTimer=null;
function setText(selector,key){const e=$(selector);if(e)e.textContent=copy()[key]}
function setHtml(selector,key){const e=$(selector);if(e)e.innerHTML=copy()[key]}
function applyLanguage(){const s=copy();document.documentElement.lang=currentLanguage;document.title=s.title;$('meta[name="description"]')?.setAttribute('content',s.desc);$('#languageSelect').value=currentLanguage;[['header .brand span:last-child','brand'],['.nav-links a:nth-child(1)','navCompress'],['.nav-links a:nth-child(2)','navPrivacy'],['.nav-links a:nth-child(3)','navUse'],['.compress-hero .eyebrow','eyebrow'],['.panel-title','panel'],['.panel-note','note'],['.file-button','choose'],['#dropLabel','drop'],['#qualityLabel','quality'],['#formatLabel','format'],['#resizeLabel','resize'],['.result-row > div:nth-child(1) span','original'],['.result-row > div:nth-child(2) span','compressed'],['.result-row > div:nth-child(3) span','saved'],['#dimensionsLabel','dimensions'],['#outputDimensionsLabel','outputDimensions'],['#downloadButton','download'],['.guide .eyebrow','guideEyebrow'],['.guide-list > div:nth-child(1) h3','g1'],['.guide-list > div:nth-child(1) p','g1p'],['.guide-list > div:nth-child(2) h3','g2'],['.guide-list > div:nth-child(2) p','g2p'],['.guide-list > div:nth-child(3) h3','g3'],['.guide-list > div:nth-child(3) p','g3p'],['.faq .eyebrow','faq'],['.faq-list details:nth-child(1) summary','faq1'],['.faq-list details:nth-child(1) p','faq1p'],['.faq-list details:nth-child(2) summary','faq2'],['.faq-list details:nth-child(2) p','faq2p'],['.faq-list details:nth-child(3) summary','faq3'],['.faq-list details:nth-child(3) p','faq3p'],['.site-footer > span','brand'],['.site-footer a:nth-child(1)','footerCompress'],['.site-footer a:nth-child(2)','footerPrivacy']].forEach(([a,b])=>setText(a,b));setText('.compress-hero .lede','lede');setHtml('h1','hero');setHtml('.guide h2','guideTitle');setHtml('.faq h2','faqTitle');$('.privacy-strip p').replaceChildren(Object.assign(document.createElement('strong'),{textContent:s.privacy}),document.createTextNode(' '+s.privacyCopy));if(!sourceFile)status.textContent=s.ready}
function formatBytes(bytes){if(bytes<1024)return`${bytes} B`;if(bytes<1048576)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1048576).toFixed(2)} MB`}
function setStatus(text,type=''){status.textContent=text;status.classList.toggle('is-error',type==='error');status.classList.toggle('is-working',type==='working');status.classList.toggle('is-success',type==='success')}
function cleanupSource(){if(source?.close)try{source.close()}catch{}source=null;if(sourceObjectUrl){URL.revokeObjectURL(sourceObjectUrl);sourceObjectUrl=null}}
function cleanupOutput(){if(outputUrl){URL.revokeObjectURL(outputUrl);outputUrl=null}preview.removeAttribute('src');downloadButton.removeAttribute('href');downloadButton.classList.add('disabled');downloadButton.setAttribute('aria-disabled','true')}
function sourceWidth(){return source?.width||source?.naturalWidth||0}function sourceHeight(){return source?.height||source?.naturalHeight||0}
async function decode(file){if('createImageBitmap'in window){try{return await createImageBitmap(file,{imageOrientation:'from-image'})}catch{}}return await new Promise((resolve,reject)=>{const u=URL.createObjectURL(file);const img=new Image();img.onload=()=>{sourceObjectUrl=u;resolve(img)};img.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('decode'))};img.src=u})}
async function loadFile(file){if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)){setStatus(copy().selectImage,'error');return}if(file.size>MAX_FILE_BYTES){setStatus(copy().tooLarge,'error');return}encodeToken++;cleanupSource();cleanupOutput();sourceFile=file;setStatus(copy().working,'working');try{source=await decode(file);if(!sourceWidth()||!sourceHeight())throw new Error();controls.hidden=false;originalSize.textContent=formatBytes(file.size);dimensions.textContent=`${sourceWidth().toLocaleString()} × ${sourceHeight().toLocaleString()}`;const name=document.createElement('strong');name.textContent=file.name;const meta=document.createElement('span');meta.textContent=`${formatBytes(file.size)} · ${file.type.replace('image/','').toUpperCase()}`;dropZone.replaceChildren(name,meta);await compress()}catch(e){console.warn(e);sourceFile=null;setStatus(copy().decodeError,'error')}}
function targetSize(){let w=sourceWidth(),h=sourceHeight();const edge=resize.value==='original'?Infinity:Number(resize.value);if(Number.isFinite(edge)&&Math.max(w,h)>edge){const s=edge/Math.max(w,h);w=Math.max(1,Math.round(w*s));h=Math.max(1,Math.round(h*s))}if(w*h>MAX_CANVAS_PIXELS){const s=Math.sqrt(MAX_CANVAS_PIXELS/(w*h));w=Math.max(1,Math.floor(w*s));h=Math.max(1,Math.floor(h*s))}return[w,h]}
function mimeAndExt(){if(format.value==='jpeg')return['image/jpeg','jpg'];if(format.value==='png')return['image/png','png'];return['image/webp','webp']}
async function canvasBlob(canvas,mime,q){return await new Promise(resolve=>canvas.toBlob(resolve,mime,q))}
async function compress(){if(!sourceFile||!source)return;const token=++encodeToken;setStatus(copy().working,'working');const[w,h]=targetSize();if(w*h>MAX_CANVAS_PIXELS){setStatus(copy().tooManyPixels,'error');return}await new Promise(r=>requestAnimationFrame(r));try{const[mime,ext]=mimeAndExt();const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:mime!=='image/jpeg',willReadFrequently:false});if(!ctx)throw new Error('canvas');if(mime==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h)}ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(source,0,0,w,h);const blob=await canvasBlob(canvas,mime,mime==='image/png'?undefined:Number(quality.value)/100);canvas.width=1;canvas.height=1;if(token!==encodeToken)return;if(!blob)throw new Error('encode');cleanupOutput();outputUrl=URL.createObjectURL(blob);preview.src=outputUrl;downloadButton.href=outputUrl;const base=(sourceFile.name.replace(/\.[^.]+$/,'')||'image').slice(0,120);downloadButton.download=`${base}-compressed.${ext}`;downloadButton.classList.remove('disabled');downloadButton.setAttribute('aria-disabled','false');compressedSize.textContent=formatBytes(blob.size);const saved=Math.round((1-blob.size/sourceFile.size)*100);savedSize.textContent=saved>=0?`${saved}%`:`+${Math.abs(saved)}%`;outputDimensions.textContent=`${w.toLocaleString()} × ${h.toLocaleString()}`;setStatus(copy().updated,'success')}catch(e){console.warn(e);setStatus(copy().encodeError,'error')}}
function schedule(){clearTimeout(debounceTimer);qualityValue.textContent=quality.value;quality.disabled=format.value==='png';debounceTimer=setTimeout(compress,160)}
fileInput.addEventListener('change',()=>loadFile(fileInput.files?.[0]));['dragenter','dragover'].forEach(n=>dropZone.addEventListener(n,e=>{e.preventDefault();dropZone.classList.add('is-dragover')}));['dragleave','drop'].forEach(n=>dropZone.addEventListener(n,e=>{e.preventDefault();dropZone.classList.remove('is-dragover')}));dropZone.addEventListener('drop',e=>loadFile(e.dataTransfer.files?.[0]));quality.addEventListener('input',schedule);format.addEventListener('change',schedule);resize.addEventListener('change',schedule);downloadButton.addEventListener('click',e=>{if(!outputUrl)e.preventDefault()});$('#languageSelect').addEventListener('change',e=>{currentLanguage=e.target.value;localStorage.setItem('site-language',currentLanguage);applyLanguage()});window.addEventListener('beforeunload',()=>{cleanupSource();cleanupOutput()});applyLanguage();qualityValue.textContent=quality.value;reportVisit();