#ifndef MOZC_REWRITER_AI_REWRITER_H_
#define MOZC_REWRITER_AI_REWRITER_H_

#include <string>

#include "rewriter/rewriter_interface.h"

namespace mozc {

namespace dictionary {
class DictionaryInterface;
}  // namespace dictionary

// Reorders only the candidates already generated by Mozc.  The ranker is
// optional: any failure leaves |segments| untouched and returns false.
class AiRewriter final : public RewriterInterface {
 public:
  explicit AiRewriter(
      std::wstring pipe_name = L"\\\\.\\pipe\\ai_ime_ranker");
  AiRewriter(
      const dictionary::DictionaryInterface* dictionary,
      std::wstring pipe_name = L"\\\\.\\pipe\\ai_ime_ranker");

  int capability(const ConversionRequest& request) const override;
  std::optional<ResizeSegmentsRequest> CheckResizeSegmentsRequest(
      const ConversionRequest& request,
      const Segments& segments) const override;
  bool Rewrite(const ConversionRequest& request,
               Segments* segments) const override;

 private:
  const dictionary::DictionaryInterface* dictionary_;
  std::wstring pipe_name_;
};

}  // namespace mozc

#endif  // MOZC_REWRITER_AI_REWRITER_H_
