(()=>{'use strict';
const $=s=>document.querySelector(s),MAX_DB_BYTES=256*1024*1024,PAGE_SIZE=200,HISTORY_MAX=12;
let worker=null,reqId=0,pending=new Map(),lang=localStorage.getItem('sqlite-lite-language')||'ja',history=[],lastResult={columns:[],rows:[],truncated:false},page=0,currentFileName='demo.sqlite',dirty=false,dbSnapshot=null,busy=false,runGeneration=0,inTransaction=false,currentSchema=[];
const P={ja:{title:'SQLite LITE — ブラウザSQLiteワークベンチ',ready:'準備完了',opening:'DBを開いています…',opened:'DBを開きました',invalid:'SQLiteファイルを開けません',tooLarge:'DBが大きすぎます（上限256MB）',run:'▶ 実行',cancel:'キャンセル',running:'Workerで実行中…',restarting:'DBを安全なスナップショットから復元中…',cancelled:'クエリをキャンセルしました',done:'実行完了',error:'SQLエラー',noTables:'テーブル/ビューはありません',empty:'結果はありません',truncated:'先頭5000行で打ち切り',captured:'件を表示対象に取得',changed:'変更行',saved:'保存しました',csvEmpty:'CSVに保存できる結果がありません',dependency:'SQLite Workerを起動できませんでした',firstOnly:'一度に1つのSQL文を実行します',file:'ファイル',size:'サイズ',state:'状態',modified:'変更あり',clean:'未変更',transaction:'トランザクション中',prev:'← 前',next:'次 →',page:'ページ',format:'整形',plan:'実行計画',exportDb:'DB保存',exportCsv:'CSV保存',demo:'デモDB'},en:{title:'SQLite LITE — Browser SQLite workbench',ready:'Ready',opening:'Opening database…',opened:'Database opened',invalid:'Could not open SQLite database',tooLarge:'Database is too large (256 MB max)',run:'▶ Run',cancel:'Cancel',running:'Running in worker…',restarting:'Restoring database from the last safe snapshot…',cancelled:'Query cancelled',done:'Query complete',error:'SQL error',noTables:'No tables or views',empty:'No result rows',truncated:'truncated at first 5,000 rows',captured:'rows captured for display',changed:'rows changed',saved:'Saved',csvEmpty:'No tabular result to export',dependency:'Could not start SQLite worker',firstOnly:'Run one SQL statement at a time',file:'File',size:'Size',state:'State',modified:'Modified',clean:'Clean',transaction:'Transaction active',prev:'← Prev',next:'Next →',page:'Page',format:'Format',plan:'Explain plan',exportDb:'Save DB',exportCsv:'Save CSV',demo:'Demo DB'},zh:{title:'SQLite LITE — 浏览器SQLite工作台',ready:'准备完成',opening:'正在打开数据库…',opened:'数据库已打开',invalid:'无法打开SQLite数据库',tooLarge:'数据库过大（最大256MB）',run:'▶ 执行',cancel:'取消',running:'正在Worker中执行…',restarting:'正在从安全快照恢复数据库…',cancelled:'查询已取消',done:'执行完成',error:'SQL错误',noTables:'没有表或视图',empty:'没有结果',truncated:'仅保留前5000行',captured:'行已读取用于显示',changed:'更改行数',saved:'已保存',csvEmpty:'没有可导出的表格结果',dependency:'无法启动SQLite Worker',firstOnly:'一次执行一个SQL语句',file:'文件',size:'大小',state:'状态',modified:'已修改',clean:'未修改',transaction:'事务进行中',prev:'← 上一页',next:'下一页 →',page:'页',format:'格式化',plan:'执行计划',exportDb:'保存DB',exportCsv:'保存CSV',demo:'演示DB'},ko:{title:'SQLite LITE — 브라우저 SQLite 작업대',ready:'준비 완료',opening:'DB 여는 중…',opened:'DB를 열었습니다',invalid:'SQLite DB를 열 수 없습니다',tooLarge:'DB가 너무 큽니다 (최대256MB)',run:'▶ 실행',cancel:'취소',running:'Worker에서 실행 중…',restarting:'안전한 스냅샷에서 DB 복원 중…',cancelled:'쿼리를 취소했습니다',done:'실행 완료',error:'SQL 오류',noTables:'테이블/뷰가 없습니다',empty:'결과가 없습니다',truncated:'처음5000행에서 제한',captured:'행을 표시용으로 읽음',changed:'변경 행',saved:'저장됨',csvEmpty:'CSV로 저장할 결과가 없습니다',dependency:'SQLite Worker를 시작할 수 없습니다',firstOnly:'한 번에 하나의 SQL 문을 실행합니다',file:'파일',size:'크기',state:'상태',modified:'변경됨',clean:'변경 없음',transaction:'트랜잭션 진행 중',prev:'← 이전',next:'다음 →',page:'페이지',format:'정리',plan:'실행 계획',exportDb:'DB 저장',exportCsv:'CSV 저장',demo:'데모 DB'}};
const t=k=>(P[lang]||P.en)[k]||k;
function fmtBytes(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`}
function setStatus(s){$('#status').textContent=s}function setDirty(v){dirty=v;$('#dbState').textContent=inTransaction?t('transaction'):(v?t('modified'):t('clean'))}
function safeName(v){return String(v||'database').replace(/[\\/:*?"<>|\x00-\x1f]/g,'_').slice(0,120)||'database'}
function validateMagic(bytes){const magic='SQLite format 3\u0000';if(bytes.length<magic.length)return false;for(let i=0;i<magic.length;i++)if(bytes[i]!==magic.charCodeAt(i))return false;return true}
function terminateWorker(reason='cancelled'){if(worker){worker.terminate();worker=null}for(const [,p]of pending){const e=new Error(reason);e.code=reason;p.reject(e)}pending.clear()}
function spawnWorker(){terminateWorker('replaced');worker=new Worker('./db-worker.js');worker.onerror=e=>{console.warn(e);for(const[,p]of pending)p.reject(new Error('worker'));pending.clear();setStatus(t('dependency'))}}
function call(action,payload={},transfer=[]){if(!worker)spawnWorker();const id=++reqId;return new Promise((resolve,reject)=>{pending.set(id,{resolve,reject});worker.postMessage({id,action,payload},transfer)})}
function onWorkerMessage(e){const {id,ok,result,error}=e.data||{},p=pending.get(id);if(!p)return;pending.delete(id);ok?p.resolve(result):p.reject(new Error(error||'Worker error'))}
function bindWorker(){if(worker)worker.onmessage=onWorkerMessage}
function ensureWorker(){if(!worker){spawnWorker();bindWorker()}}
function applyLanguage(){document.documentElement.lang=lang;document.title=t('title');$('#languageSelect').value=lang;$('#run').textContent=t('run');$('#cancelQuery').textContent=t('cancel');$('#formatSql').textContent=t('format');$('#explainPlan').textContent=t('plan');$('#exportDb').textContent=t('exportDb');$('#exportCsv').textContent=t('exportCsv');$('#prevPage').textContent=t('prev');$('#nextPage').textContent=t('next');$('#fileLabel').textContent=t('file');$('#sizeLabel').textContent=t('size');$('#stateLabel').textContent=t('state');setDirty(dirty);renderResult();renderSchema(currentSchema)}
function renderSchema(rows=currentSchema){currentSchema=rows||[];const box=$('#schema');box.replaceChildren();if(!currentSchema.length){const e=document.createElement('div');e.className='empty';e.textContent=t('noTables');box.append(e);return}let last='';for(const item of currentSchema){if(item.type!==last){last=item.type;const h=document.createElement('div');h.className='schema-group';h.textContent=String(item.type).toUpperCase();box.append(h)}const b=document.createElement('button');b.type='button';b.className='table-item';b.textContent=`▦ ${item.name}`;b.title=item.name;b.onclick=()=>{$('#query').value=`SELECT * FROM ${item.quoted} LIMIT 5000;`;runQuery()};box.append(b)}}
function addHistory(sql){history=history.filter(x=>x!==sql);history.unshift(sql);history=history.slice(0,HISTORY_MAX);const box=$('#history');box.replaceChildren();for(const q of history){const b=document.createElement('button');b.type='button';b.textContent=q.replace(/\s+/g,' ').slice(0,80);b.title=q;b.onclick=()=>{$('#query').value=q};box.append(b)}}
function renderResult(){const out=$('#output');out.replaceChildren();const {columns=[],rows=[],truncated=false}=lastResult,total=rows.length;if(!columns.length){const e=document.createElement('div');e.className='empty';e.textContent=t('empty');out.append(e);$('#resultMeta').textContent='—';$('#prevPage').disabled=true;$('#nextPage').disabled=true;$('#pageLabel').textContent='';$('#exportCsv').disabled=true;return}const maxPage=Math.max(0,Math.ceil(total/PAGE_SIZE)-1);page=Math.min(page,maxPage);const start=page*PAGE_SIZE,end=Math.min(start+PAGE_SIZE,total),table=document.createElement('table'),thead=document.createElement('thead'),hr=document.createElement('tr');for(const c of columns){const th=document.createElement('th');th.textContent=String(c);hr.append(th)}thead.append(hr);table.append(thead);const tbody=document.createElement('tbody');for(const row of rows.slice(start,end)){const tr=document.createElement('tr');for(const v of row){const td=document.createElement('td');td.textContent=v==null?'NULL':String(v);td.title=td.textContent;tr.append(td)}tbody.append(tr)}table.append(tbody);out.append(table);$('#resultMeta').textContent=`${total.toLocaleString()} ${t('captured')}${truncated?' · '+t('truncated'):''}`;$('#pageLabel').textContent=`${t('page')} ${page+1}/${maxPage+1}`;$('#prevPage').disabled=page===0;$('#nextPage').disabled=page>=maxPage;$('#exportCsv').disabled=!rows.length}
function showError(message){const div=document.createElement('div');div.className='empty';div.style.color='var(--danger)';div.textContent=message;$('#output').replaceChildren(div)}
function hasLikelyMultipleStatements(sql){let quote=null,comment=null,foundEnd=false;for(let i=0;i<sql.length;i++){const c=sql[i],n=sql[i+1];if(comment==='line'){if(c==='\n')comment=null;continue}if(comment==='block'){if(c==='*'&&n==='/'){comment=null;i++}continue}if(quote){if(c===quote){if(sql[i+1]===quote)i++;else quote=null}continue}if(c==='-'&&n==='-'){comment='line';i++;continue}if(c==='/'&&n==='*'){comment='block';i++;continue}if(c==='"'||c==="'"||c==='`'){quote=c;continue}if(c===';'){if(foundEnd||sql.slice(i+1).trim())return true;foundEnd=true}}return false}
function setBusy(v){busy=v;$('#run').disabled=v;$('#cancelQuery').disabled=!v;$('#formatSql').disabled=v;$('#explainPlan').disabled=v;$('#dbInput').disabled=v;$('#exportDb').disabled=v}
async function runQuery(customSql=null){if(busy)return;const sql=(customSql??$('#query').value).trim();if(!sql)return;if(hasLikelyMultipleStatements(sql)){setStatus(t('firstOnly'));return}const generation=++runGeneration;setBusy(true);setStatus(t('running'));try{ensureWorker();const r=await call('query',{sql});if(generation!==runGeneration)return;lastResult={columns:r.columns||[],rows:r.rows||[],truncated:!!r.truncated};page=0;inTransaction=!!r.inTransaction;if(r.snapshot){dbSnapshot=new Uint8Array(r.snapshot);dirty=true}if(r.mutating)dirty=true;if(r.schema)renderSchema(r.schema);addHistory(sql);renderResult();setDirty(dirty);setStatus(r.changed?`${t('done')} · ${r.changed} ${t('changed')}`:t('done'))}catch(e){if(e.code==='cancelled'||e.code==='replaced')return;console.warn(e);lastResult={columns:[],rows:[],truncated:false};renderResult();showError(String(e.message||e));setStatus(t('error'))}finally{if(generation===runGeneration)setBusy(false)}}
async function cancelQuery(){if(!busy)return;runGeneration++;setBusy(false);setStatus(t('cancelled'));terminateWorker('cancelled');try{await restoreWorker()}catch(e){console.warn(e);setStatus(t('dependency'))}}
async function restoreWorker(){setStatus(t('restarting'));spawnWorker();bindWorker();if(dbSnapshot){const copy=dbSnapshot.slice(),buf=copy.buffer;const r=await call('open',{bytes:buf},[buf]);currentSchema=r.schema||[];inTransaction=false;renderSchema(currentSchema)}else await makeDemo(false);setDirty(dirty);setStatus(t('ready'))}
function formatSql(){const q=$('#query');q.value=q.value.trim().replace(/\s+(FROM|WHERE|GROUP\s+BY|ORDER\s+BY|HAVING|LIMIT|OFFSET|JOIN|LEFT\s+JOIN|RIGHT\s+JOIN|INNER\s+JOIN|UNION(?:\s+ALL)?)\s+/gi,'\n$1 ').replace(/,\s*/g,',\n  ')}
function explain(){const sql=$('#query').value.trim().replace(/;\s*$/,'');if(sql)runQuery('EXPLAIN QUERY PLAN '+sql)}
function csvCell(v){let s=v==null?'':String(v);if(/^[=+\-@]/.test(s))s="'"+s;return`"${s.replace(/"/g,'""')}"`}
function download(name,blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function exportCsv(){if(!lastResult.rows.length){setStatus(t('csvEmpty'));return}const lines=[lastResult.columns,...lastResult.rows].map(r=>r.map(csvCell).join(',')).join('\r\n');download('query-result.csv',new Blob(['\uFEFF'+lines],{type:'text/csv;charset=utf-8'}));setStatus(t('saved'))}
async function exportDb(){try{ensureWorker();const r=await call('export');if(r.snapshot){const bytes=new Uint8Array(r.snapshot);dbSnapshot=bytes.slice();download(safeName(currentFileName.replace(/\.(db|sqlite|sqlite3)$/i,'')||'database')+'.sqlite',new Blob([bytes],{type:'application/vnd.sqlite3'}));if(!inTransaction){dirty=false;setDirty(false)}setStatus(t('saved'))}}catch(e){console.warn(e);setStatus(t('error'))}}
async function openFile(file){if(!file)return;if(file.size>MAX_DB_BYTES){setStatus(t('tooLarge'));return}setStatus(t('opening'));try{const bytes=new Uint8Array(await file.arrayBuffer());if(!validateMagic(bytes))throw new Error('magic');terminateWorker('replaced');spawnWorker();bindWorker();dbSnapshot=bytes.slice();const send=bytes.buffer,r=await call('open',{bytes:send},[send]);currentFileName=file.name;$('#dbName').textContent=file.name;$('#dbSize').textContent=fmtBytes(file.size);dirty=false;inTransaction=false;currentSchema=r.schema||[];renderSchema(currentSchema);$('#query').value="SELECT name, type FROM sqlite_master WHERE type IN ('table','view') ORDER BY name;";lastResult={columns:[],rows:[],truncated:false};renderResult();setDirty(false);setStatus(t('opened'))}catch(e){console.warn(e);setStatus(t('invalid'))}finally{$('#dbInput').value=''}}
async function makeDemo(showStatus=true){terminateWorker('replaced');spawnWorker();bindWorker();const r=await call('demo');dbSnapshot=new Uint8Array(r.snapshot);currentSchema=r.schema||[];currentFileName='demo.sqlite';$('#dbName').textContent=t('demo');$('#dbSize').textContent=fmtBytes(dbSnapshot.length);dirty=false;inTransaction=false;renderSchema(currentSchema);setDirty(false);if(showStatus)setStatus(t('ready'))}
async function init(){applyLanguage();if(!('Worker'in window)){setStatus(t('dependency'));return}try{await makeDemo(false);setStatus(t('ready'))}catch(e){console.warn(e);setStatus(t('dependency'));return}$('#dbInput').onchange=e=>openFile(e.target.files?.[0]);const dz=$('#fileZone');['dragenter','dragover'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{if(!busy)openFile(e.dataTransfer.files?.[0])});$('#run').onclick=()=>runQuery();$('#cancelQuery').onclick=cancelQuery;$('#formatSql').onclick=formatSql;$('#explainPlan').onclick=explain;$('#exportDb').onclick=exportDb;$('#exportCsv').onclick=exportCsv;$('#prevPage').onclick=()=>{if(page>0){page--;renderResult()}};$('#nextPage').onclick=()=>{page++;renderResult()};$('#query').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();runQuery()}else if(e.key==='Tab'){e.preventDefault();const q=e.currentTarget,s=q.selectionStart;q.setRangeText('  ',s,q.selectionEnd,'end')}};$('#languageSelect').onchange=e=>{lang=e.target.value;localStorage.setItem('sqlite-lite-language',lang);applyLanguage()};window.addEventListener('beforeunload',()=>terminateWorker('close'));setBusy(false)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();