(()=>{'use strict';
const $=s=>document.querySelector(s);const MAX_DB_BYTES=256*1024*1024,MAX_CAPTURE_ROWS=5000,PAGE_SIZE=200,HISTORY_MAX=12;
let SQL=null,db=null,lang=localStorage.getItem('sqlite-lite-language')||'ja',history=[],lastResult={columns:[],rows:[],truncated:false},page=0,currentFileName='demo.sqlite',dirty=false;
const P={ja:{title:'SQLite LITE — ブラウザSQLiteワークベンチ',ready:'準備完了',opening:'DBを開いています…',opened:'DBを開きました',invalid:'SQLiteファイルを開けません',tooLarge:'DBが大きすぎます（上限256MB）',run:'▶ 実行',running:'実行中…',done:'実行完了',error:'SQLエラー',noTables:'テーブル/ビューはありません',empty:'結果はありません',rows:'行',captured:'件を表示対象に取得',truncated:'先頭5000行で打ち切り',changed:'変更行',saved:'保存しました',csvEmpty:'CSVに保存できる結果がありません',dependency:'SQLiteエンジンを読み込めませんでした',firstOnly:'一度に1つのSQL文を実行します',file:'ファイル',size:'サイズ',state:'状態',modified:'変更あり',clean:'未変更',prev:'← 前',next:'次 →',page:'ページ',format:'整形',plan:'実行計画',exportDb:'DB保存',exportCsv:'CSV保存',demo:'デモDB'},en:{title:'SQLite LITE — Browser SQLite workbench',ready:'Ready',opening:'Opening database…',opened:'Database opened',invalid:'Could not open SQLite database',tooLarge:'Database is too large (256 MB max)',run:'▶ Run',running:'Running…',done:'Query complete',error:'SQL error',noTables:'No tables or views',empty:'No result rows',rows:'rows',captured:'rows captured for display',truncated:'truncated at first 5,000 rows',changed:'rows changed',saved:'Saved',csvEmpty:'No tabular result to export',dependency:'SQLite engine failed to load',firstOnly:'Run one SQL statement at a time',file:'File',size:'Size',state:'State',modified:'Modified',clean:'Clean',prev:'← Prev',next:'Next →',page:'Page',format:'Format',plan:'Explain plan',exportDb:'Save DB',exportCsv:'Save CSV',demo:'Demo DB'},zh:{title:'SQLite LITE — 浏览器SQLite工作台',ready:'准备完成',opening:'正在打开数据库…',opened:'数据库已打开',invalid:'无法打开SQLite数据库',tooLarge:'数据库过大（最大256MB）',run:'▶ 执行',running:'执行中…',done:'执行完成',error:'SQL错误',noTables:'没有表或视图',empty:'没有结果',rows:'行',captured:'行已读取用于显示',truncated:'仅保留前5000行',changed:'更改行数',saved:'已保存',csvEmpty:'没有可导出的表格结果',dependency:'SQLite引擎加载失败',firstOnly:'一次执行一个SQL语句',file:'文件',size:'大小',state:'状态',modified:'已修改',clean:'未修改',prev:'← 上一页',next:'下一页 →',page:'页',format:'格式化',plan:'执行计划',exportDb:'保存DB',exportCsv:'保存CSV',demo:'演示DB'},ko:{title:'SQLite LITE — 브라우저 SQLite 작업대',ready:'준비 완료',opening:'DB 여는 중…',opened:'DB를 열었습니다',invalid:'SQLite DB를 열 수 없습니다',tooLarge:'DB가 너무 큽니다 (최대256MB)',run:'▶ 실행',running:'실행 중…',done:'실행 완료',error:'SQL 오류',noTables:'테이블/뷰가 없습니다',empty:'결과가 없습니다',rows:'행',captured:'행을 표시용으로 읽음',truncated:'처음5000행에서 제한',changed:'변경 행',saved:'저장됨',csvEmpty:'CSV로 저장할 결과가 없습니다',dependency:'SQLite 엔진 로드 실패',firstOnly:'한 번에 하나의 SQL 문을 실행합니다',file:'파일',size:'크기',state:'상태',modified:'변경됨',clean:'변경 없음',prev:'← 이전',next:'다음 →',page:'페이지',format:'정리',plan:'실행 계획',exportDb:'DB 저장',exportCsv:'CSV 저장',demo:'데모 DB'}};
const t=k=>(P[lang]||P.en)[k]||k;function fmtBytes(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`}function setStatus(s){$('#status').textContent=s}
function setDirty(v){dirty=v;$('#dbState').textContent=v?t('modified'):t('clean')}
function qIdent(v){return`"${String(v).replace(/"/g,'""')}"`}
function safeName(v){return String(v||'database').replace(/[\\/:*?"<>|\x00-\x1f]/g,'_').slice(0,120)||'database'}
function closeDb(){if(db){try{db.close()}catch{}db=null}}
function applyLanguage(){document.documentElement.lang=lang;document.title=t('title');$('#languageSelect').value=lang;$('#run').textContent=t('run');$('#formatSql').textContent=t('format');$('#explainPlan').textContent=t('plan');$('#exportDb').textContent=t('exportDb');$('#exportCsv').textContent=t('exportCsv');$('#prevPage').textContent=t('prev');$('#nextPage').textContent=t('next');$('#fileLabel').textContent=t('file');$('#sizeLabel').textContent=t('size');$('#stateLabel').textContent=t('state');if(db)setDirty(dirty);renderResult();renderSchema()}
function renderSchema(){const box=$('#schema');box.replaceChildren();if(!db)return;let rows=[];try{rows=db.exec("SELECT type,name FROM sqlite_master WHERE type IN ('table','view') AND name NOT LIKE 'sqlite_%' ORDER BY type,name")[0]?.values||[]}catch{}if(!rows.length){const e=document.createElement('div');e.className='empty';e.textContent=t('noTables');box.append(e);return}let last='';for(const [type,name] of rows){if(type!==last){last=type;const h=document.createElement('div');h.className='schema-group';h.textContent=type.toUpperCase();box.append(h)}const b=document.createElement('button');b.type='button';b.className='table-item';b.textContent=`▦ ${name}`;b.title=String(name);b.onclick=()=>{$('#query').value=`SELECT * FROM ${qIdent(name)} LIMIT 5000;`;runQuery()};box.append(b)}}
function addHistory(sql){if(!sql)return;history=history.filter(x=>x!==sql);history.unshift(sql);history=history.slice(0,HISTORY_MAX);const box=$('#history');box.replaceChildren();for(const q of history){const b=document.createElement('button');b.type='button';b.textContent=q.replace(/\s+/g,' ').slice(0,80);b.title=q;b.onclick=()=>{$('#query').value=q};box.append(b)}}
function renderResult(){const out=$('#output');out.replaceChildren();const {columns,rows,truncated}=lastResult;const total=rows.length;if(!columns.length){const e=document.createElement('div');e.className='empty';e.textContent=t('empty');out.append(e);$('#resultMeta').textContent='—';$('#prevPage').disabled=true;$('#nextPage').disabled=true;$('#pageLabel').textContent='';$('#exportCsv').disabled=true;return}const maxPage=Math.max(0,Math.ceil(total/PAGE_SIZE)-1);page=Math.min(page,maxPage);const start=page*PAGE_SIZE,end=Math.min(start+PAGE_SIZE,total);const table=document.createElement('table'),thead=document.createElement('thead'),hr=document.createElement('tr');for(const c of columns){const th=document.createElement('th');th.textContent=String(c);hr.append(th)}thead.append(hr);table.append(thead);const tbody=document.createElement('tbody');for(const row of rows.slice(start,end)){const tr=document.createElement('tr');for(const v of row){const td=document.createElement('td');td.textContent=v==null?'NULL':typeof v==='object'?JSON.stringify(v):String(v);td.title=td.textContent;tr.append(td)}tbody.append(tr)}table.append(tbody);out.append(table);$('#resultMeta').textContent=`${total.toLocaleString()} ${t('captured')}${truncated?' · '+t('truncated'):''}`;$('#pageLabel').textContent=`${t('page')} ${page+1}/${maxPage+1}`;$('#prevPage').disabled=page===0;$('#nextPage').disabled=page>=maxPage;$('#exportCsv').disabled=!rows.length}
function isProbablyMutating(sql){const s=sql.replace(/^\s*(?:--[^\n]*\n|\/\*[\s\S]*?\*\/\s*)*/,'').toUpperCase();return /^(INSERT|UPDATE|DELETE|REPLACE|CREATE|DROP|ALTER|VACUUM|REINDEX|ANALYZE|ATTACH|DETACH|PRAGMA\s+(?!TABLE_INFO|INDEX_LIST|INDEX_INFO|DATABASE_LIST|COMPILE_OPTIONS))/i.test(s)}
function hasLikelyMultipleStatements(sql){let quote=null,comment=null,count=0;for(let i=0;i<sql.length;i++){const c=sql[i],n=sql[i+1];if(comment==='line'){if(c==='\n')comment=null;continue}if(comment==='block'){if(c==='*'&&n==='/'){comment=null;i++}continue}if(quote){if(c===quote){if(sql[i+1]===quote)i++;else quote=null}continue}if(c==='-'&&n==='-'){comment='line';i++;continue}if(c==='/'&&n==='*'){comment='block';i++;continue}if(c==='"'||c==="'"||c==='`'){quote=c;continue}if(c===';'){if(sql.slice(i+1).trim())count++}}return count>0}
function runQuery(customSql=null){if(!db)return;const sql=(customSql??$('#query').value).trim();if(!sql)return;if(hasLikelyMultipleStatements(sql)){setStatus(t('firstOnly'));return}setStatus(t('running'));$('#run').disabled=true;requestAnimationFrame(()=>{let stmt;try{stmt=db.prepare(sql);const columns=stmt.getColumnNames();const rows=[];let truncated=false;if(columns.length){while(stmt.step()){if(rows.length<MAX_CAPTURE_ROWS)rows.push(stmt.get());else{truncated=true;break}}lastResult={columns,rows,truncated};page=0}else{stmt.step();lastResult={columns:[],rows:[],truncated:false}}stmt.free();stmt=null;const changed=db.getRowsModified();const mutating=isProbablyMutating(sql)||changed>0;if(mutating){setDirty(true);renderSchema()}addHistory(sql);renderResult();setStatus(changed?`${t('done')} · ${changed} ${t('changed')}`:t('done'))}catch(e){if(stmt)try{stmt.free()}catch{}lastResult={columns:[],rows:[],truncated:false};renderResult();const m=String(e?.message||e);const div=document.createElement('div');div.className='empty';div.style.color='var(--danger)';div.textContent=m;$('#output').replaceChildren(div);setStatus(t('error'))}finally{$('#run').disabled=false}},0)}
function formatSql(){const q=$('#query');q.value=q.value.trim().replace(/\s+(FROM|WHERE|GROUP\s+BY|ORDER\s+BY|HAVING|LIMIT|OFFSET|JOIN|LEFT\s+JOIN|RIGHT\s+JOIN|INNER\s+JOIN|UNION(?:\s+ALL)?)\s+/gi,'\n$1 ').replace(/,\s*/g,',\n  ')}
function explain(){let sql=$('#query').value.trim().replace(/;\s*$/,'');if(!sql)return;runQuery('EXPLAIN QUERY PLAN '+sql)}
function csvCell(v){let s=v==null?'':v instanceof Uint8Array?`[BLOB ${v.length} bytes]`:String(v);if(/^[=+\-@]/.test(s))s="'"+s;return`"${s.replace(/"/g,'""')}"`}
function download(name,blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1200)}
function exportCsv(){if(!lastResult.rows.length){setStatus(t('csvEmpty'));return}const lines=[lastResult.columns,...lastResult.rows].map(r=>r.map(csvCell).join(',')).join('\r\n');download('query-result.csv',new Blob(['\uFEFF'+lines],{type:'text/csv;charset=utf-8'}));setStatus(t('saved'))}
function exportDb(){if(!db)return;const data=db.export();download(safeName(currentFileName.replace(/\.(db|sqlite|sqlite3)$/i,'')||'database')+'.sqlite',new Blob([data],{type:'application/vnd.sqlite3'}));setDirty(false);setStatus(t('saved'))}
function validateMagic(bytes){if(bytes.length<16)return false;const magic='SQLite format 3\u0000';for(let i=0;i<magic.length;i++)if(bytes[i]!==magic.charCodeAt(i))return false;return true}
async function openFile(file){if(!file)return;if(file.size>MAX_DB_BYTES){setStatus(t('tooLarge'));return}setStatus(t('opening'));try{const bytes=new Uint8Array(await file.arrayBuffer());if(!validateMagic(bytes))throw new Error('magic');closeDb();db=new SQL.Database(bytes);currentFileName=file.name;$('#dbName').textContent=file.name;$('#dbSize').textContent=fmtBytes(file.size);setDirty(false);renderSchema();$('#query').value="SELECT name, type FROM sqlite_master WHERE type IN ('table','view') ORDER BY name;";lastResult={columns:[],rows:[],truncated:false};renderResult();setStatus(t('opened'))}catch(e){console.warn(e);setStatus(t('invalid'))}finally{$('#dbInput').value=''}}
function makeDemo(){closeDb();db=new SQL.Database();db.run('CREATE TABLE notes(id INTEGER PRIMARY KEY, title TEXT, category TEXT, score REAL, created_at TEXT);');db.run("INSERT INTO notes(title,category,score,created_at) VALUES ('Quiet corners','place',4.8,'2026-01-12'),('A useful shortcut','workflow',4.3,'2026-02-03'),('Morning light','place',4.6,'2026-02-08'),('Tiny rituals','habit',3.9,'2026-03-10'),('One good question','workflow',4.9,'2026-03-17'),('Paper texture','design',4.1,'2026-04-01');");currentFileName='demo.sqlite';$('#dbName').textContent=t('demo');$('#dbSize').textContent=fmtBytes(db.export().length);setDirty(false);renderSchema();runQuery()}
async function init(){applyLanguage();try{if(typeof initSqlJs!=='function')throw new Error('missing');SQL=await initSqlJs({locateFile:f=>'https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/'+f});makeDemo()}catch(e){console.warn(e);setStatus(t('dependency'));document.querySelectorAll('button,input,textarea').forEach(e=>e.disabled=true);return}$('#dbInput').onchange=e=>openFile(e.target.files?.[0]);const dz=$('#fileZone');['dragenter','dragover'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>openFile(e.dataTransfer.files?.[0]));$('#run').onclick=()=>runQuery();$('#formatSql').onclick=formatSql;$('#explainPlan').onclick=explain;$('#exportDb').onclick=exportDb;$('#exportCsv').onclick=exportCsv;$('#prevPage').onclick=()=>{if(page>0){page--;renderResult()}};$('#nextPage').onclick=()=>{page++;renderResult()};$('#query').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();runQuery()}else if(e.key==='Tab'){e.preventDefault();const q=e.currentTarget,s=q.selectionStart;q.setRangeText('  ',s,q.selectionEnd,'end')}};$('#languageSelect').onchange=e=>{lang=e.target.value;localStorage.setItem('sqlite-lite-language',lang);applyLanguage()};window.addEventListener('beforeunload',closeDb)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();